### ISSUE TITLE
getPath error when convert called with editor pane out of focus

### ISSUE THREAD

**Issue by vitalystr** [travs/markdown-pdf#155]
I'm trying to use convertation, an error message shows in Atom with:
```markdown-pdf: TypeError: atom.workspace.getActivePaneItem(...).getPath is not a function```. I'm using Atom version 1.16.0 and Windows 10 x64.

**Comment by holic-cl** [comment]
Same here, using Atom 1.17.2 on Linux.

**Comment by travs** [comment]
@holic-cl 
Same version and OS here, what distribution are you using?

Also can you and @vitalystr both run `atom --version` and `apm list` commands, paste the results in a [gist](https://gist.github.com/), and link here so I can get a bit more information?

**Comment by travs** [comment]
And what were the names of the files you were attempting to convert? (sorry @vitalystr it's been months, it's ok if you don't remember :smile: )

**Comment by holic-cl** [comment]
Hi, thanks for fast answer.

I can't reproduce it again, i think i removed or deactivated a package or something.

My distro is Debian testing (Stretch).

I don't know if this helps, but i did it anyway:
https://gist.github.com/holic-cl/4525b0e65eec3ee777443918f98199a4

**Comment by holic-cl** [comment]
Ok, i remembered why i got this error, was when i tried to use it, and forgot to save the buffer to a file,

The buffer must to be saved to a existing file.

**Comment by travs** [comment]
@holic-cl 
Ok great, thanks for the quick feedback.
I've tried converting without saving locally and it works fine, **however**, when I click the tree-view panel before running `convert`, I get the originally reported error.

This issue is most likely caused by a loss of focus for the pane containing the file, thus `getPath` is not a function on this pane item (the tree-view).
Fix would be a better method for getting the edited file's path, even when the pane is not in focus.
Will have a look at atom docs and see if they have a better function.
