### ISSUE TITLE
Always a [space] after a 'w', if followed by an 'i'

### ISSUE THREAD

**Issue by Spirit328** [travs/markdown-pdf#178]
### Prerequisites

* [X] Reproduced the problem in Safe Mode (may not be approriate if your error involves markdown-preview-plus): http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* [X] Checked that the issue isn't already filed: https://github.com/travs/markdown-pdf/issues)

### Issue description
Everytime a 'w' is followed by an 'i', there is a [space] between them.
Example: " ... wird ... " will render as "... w ird". 

This looks not so nicely in German and may lead to some confusion.

### Steps to reproduce

**Expected behavior:** [What you expect to happen]
Für den Event-Store wird es genau ein Informationsspeicher-System geben. Evaluation in Vorbereitung
**Actual behavior:** [What actually happens]
Für den Event-Store w ird es genau ein Informationsspeicher-System geben. Evaluation in Vorbereitung

### Input
Für den Event-Store wird es genau ein Informationsspeicher-System geben. Evaluation in Vorbereitung

If your markdown document does not contain sensitive information, it is easier to diagnose with the exact contents of the file.
You can create a gist of the file and paste the link here: https://gist.github.com

### Versions
Atom Version 1.21.1
markdown-pdf 2.10
On Windows 10

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

**Comment by Methroix** [comment]
I'm experiencing the same issue, although it's not just 'w' followed by 'i' that is affected.
When 'w' is followed by any (in my case Swedish) upper or lower case character, a space is inserted inbetween.

### Steps to reproduce
**Expected behavior:** [What you expect to happen]
wa, wA, wb, wB, wc, wC, wd, wD, we, wE, wf, wF, wg, wG, wh, wH, wi, wI, wj, wJ, wk, wK, wl, wL, wm, wM, wn, wN, wo, wO, wp, wP, wq, wQ, wr, wR, ws, wS, wt, wT, wu, wU, wv, wV, ww, wW, wx, wX, wy, wY, wz, wZ, wå, wÅ, wä, wÄ, wö, wÖ
**Actual behavior:** [What actually happens]
w a, w A, w b, w B, w c, w C, w d, w D, w e, w E, w f, w F, w g, w G, w h, w H, w i, w I, w j, w J, w k, w K, w l, w L, w m, w M, w n, w N, w o, w O, w p, w P, w q, w Q, w r, w R, w s, w S, w t, w T, w u, w U, w v, w V, w w , w W, w x, w X, w y, w Y, w z, w Z, w å, w Å, w ä, w Ä, w ö, w Ö

**Comment by travs** [comment]
Should be fixed with upgrade to puppeteer engine in mdpdf
