### ISSUE TITLE
Issue with using underscore for bold text

### ISSUE THREAD

**Issue by AxlLind** [travs/markdown-pdf#182]
### Issue description
Using the underscore syntax for bold text does not work as expected. I.e __this is bold__ does not work when there are several bold things in a row.

### Steps to reproduce

**Expected behavior:** Using bold in succession should bold different parts enclosed in __ as bold text but it does not work.

**Actual behavior:** Text between several underscores bolds the whole thing and prints actual underscores instead.

### Input
Here is the input file I'm getting the error on: https://gist.github.com/AxlLind/c5ae7a77485ca47ba31b10535692b71f

See the first section Pre-lecture. In the Forming - .... line it does not bold the text as expected. I've also gotten this issue in other files.
### Versions
Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.11
npm  3.10.10
node 6.9.5 x64
atom 1.23.1
python 2.7.10
git 2.10.1

On Mac Os 10.11.5 (15F34)

**Comment by travs** [comment]
Late reply, but for anyone reading this, this issue is certainly a bug, but it appears to be on the mdpdf side, so will raise an issue over there and link it.

For now, though, please use the `force fallback mode` on this package, and it will work as expected.

**Comment by BlueHatbRit** [comment]
_Copied here for visibility from the mdpdf issue._

MDPDF 2.0.1 now matches the latest Showdown output shown in the above comment, this was done by updating to the latest version of Showdown. If this isn't the expected behaviour then we should look at reporting it to that project and see if they think this is how the md spec should be interpreted.
