### ISSUE TITLE
Error when running converting .md file to .pdf - markdown-pdf: TypeError: mdpreview.mainModule.copyHtml is not a function

### ISSUE THREAD

**Issue by cedewey** [travs/markdown-pdf#213]
### Prerequisites

* [x ] Checked that the issue isn't already filed: https://github.com/travs/markdown-pdf/issues)

### Issue description

Error when running markdown-pdf package. 

### Steps to reproduce

**Expected behavior:** PDF file is generated

**Actual behavior:** Error occurs

markdown-pdf: TypeError: mdpreview.mainModule.copyHtml is not a function

### Versions
1.39.1

**Comment by travs** [comment]
Hey there. I know this issue is old, but this was almost certainly an issue with either the default `markdown-pdf` or installed `markdown-preview-plus` package. The backend should be much more robust now, so the fallback should be invoked much less anyway, so I will close it for now.

If anyone gets this exact error again, please paste the full error messages from the console along with other information on installed atom packages (`apm list`).
