### ISSUE TITLE
Support user styles in the output pdf?

### ISSUE THREAD

**Issue by ryangyoung** [travs/markdown-pdf#37]
Hello, 

First of all, thanks for the great package. I really like it. But I can't figure out how how to modify the look of the output. Would I have to go into the marked package and edit the CSS there? 

Apologies if this is already covered somewhere. 

Thanks, 
Ryan

**Comment by travs** [comment]
Thanks for the compliment :smile: 
Markdown-pdf applies your user styles, so you can just edit your user styles and the changes should show up in the output pdf!

**Comment by croxxx** [comment]
@travs Unfortunately markdown-pdf seems to completely *ignore everything style-related* for me. Only thing used is background color in code blocks.

This is how markdown-preview displays it:
![md-preview](https://cloud.githubusercontent.com/assets/5447834/6480667/74c2c180-c256-11e4-8cb8-a60fafa0f450.png)

And this is the resulting PDF file:
![pdf-result](https://cloud.githubusercontent.com/assets/5447834/6480670/7bf5b66a-c256-11e4-85ce-8deb935b1e57.png)

As you see not only the styles are missing (these never worked for me), but also bold font style gets ignored (see top left, *this happens since one of the last updates*).
In addition the horizontal rules get scrambled.

---
I'm using a portable version of Atom.
**UI Theme:** Isotope
**Syntax Theme:** Seti Monokai

**Comment by travs** [comment]
@croxxx Are you still getting this error?

Also, could you try this with dark solarized syntax and atom dark themes and see if it still ignores styles?

**Comment by croxxx** [comment]
Yes, this still seems to be the case.
Below are my new test results.

# Default UI and default syntax theme
### View from inside Atom
![default-markdown](https://cloud.githubusercontent.com/assets/5447834/6761517/75097822-cf54-11e4-8b94-f370bee64ae7.png)
### Resulting PDF
![default-pdf](https://cloud.githubusercontent.com/assets/5447834/6761523/7added3c-cf54-11e4-902f-62c73abe9f13.png)

# Isotope UI and seti-monokai syntax theme
### View from inside Atom
![monokai-markdown](https://cloud.githubusercontent.com/assets/5447834/6761525/7f3b2f7a-cf54-11e4-9286-11cca5d52bd7.png)
### Resulting PDF
![monokai-pdf](https://cloud.githubusercontent.com/assets/5447834/6761527/8298e98c-cf54-11e4-9966-244ac7476808.png)

---
Tested using latest versions of all plugins.
So this seems to be a result of using the seti-monokai syntax theme...

**Comment by travs** [comment]
Apologies for taking so long to get back to this; I've been busy with other things and kind of dropped this package for a bit. I'm back now though.

@croxxx 
Assuming nothing has changed on this, I'm going to modify the name of this issue and add it to a milestone so we can figure it out.

**Comment by croxxx** [comment]
In fact I didn't use Atom for documentation for a while...

**Something I didn't mention before:**
It might be useful to change the sanitize=true option of the markdown converter.
That would allow HTML to be inserted. I used HTML for pagebreaks in the output.

**Comment by travs** [comment]
@croxxx Ok, I think an option or toggle could be added for that. Please add a separate issue for this, and someone may come along and patch it

**Comment by travs** [comment]
This should be enabled now, I think I just forgot to close the issue
