### ISSUE TITLE
one deprecation calls on Atom 194.0

### ISSUE THREAD

**Issue by hiroqli** [travs/markdown-pdf#49]
I meet the following deprecation calls after just installed markdown-pdf.
![2015-04-28 10 35 09](https://cloud.githubusercontent.com/assets/29589/7361387/69e636ea-ed92-11e4-88c9-95439031284e.png)

**Comment by dragonholiday** [comment]
I meet the same problem, and I have more information about this it, just see the screenshot I uploaded. It is because that line 170:36 of file "markdown-pdf.js" calls a deprecated method, you can fix that by replacing "activePaneItem" with getActivePaneItem().
Hope that @travs can fix that in the repository.
![markdown_pdf_error](https://cloud.githubusercontent.com/assets/3395087/7385604/af9ba622-ee7b-11e4-94b5-c944226e8f21.png)

**Comment by travs** [comment]
[Refer here](https://github.com/travs/markdown-pdf/pull/51)
